name: React App Build CI

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./application-code/app-tier
        
     

      # Step 4: Build the React application in the app-tier folder
      - name: Build the application
        run: npm run build
        working-directory: ./application-code/app-tier/package.json

      # Step 5: Upload the build folder as an artifact
     # - name: Upload build artifact
      #  uses: actions/upload-artifact@v4
       # with:
        #  name: build-artifact
         # path: app-tier/build

      # Step 6: Set up Java 17
      #- name: Set up Java
       # uses: actions/setup-java@v3
        #with:
         # java-version: '17'
          #distribution: 'temurin'  # Specify the Java distribution

      # Step 7: Run SonarQube scan
     # - name: SonarQube scan
     #   run: |
     #     npx sonar-scanner \
     #       -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} \
     #       -Dsonar.sources=aws-three-tier-web-architecture-workshop/application-code/app-tier/src \
     #       -Dsonar.host.url=${{ secrets.HOST_URL }} \
     #       -Dsonar.login=${{ secrets.CSS_SONAR_TOKEN }}
